# 本机开发环境

# 配置数据源信息(此处使用了 p6spy 插件统计 SQL 执行时间，仅用于开发阶段)
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    password: root
    url: jdbc:p6spy:mysql://localhost:3306/iot?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    hikari:
      pool-name: hikari

# 配置日志文件
logging:
  level:
    tech.taoq: debug
    # org.springframework.web: debug

knife4j:
  enable: true

taoq:
  oss:
    storage-type: localFileSystem
    local-file-system:
      # 前面后面都需要加上 '/'
      root-path: /D:/upload/
    resource-handlers: false
  web:
    my-mapping-jackson2-http-message-converter: true
    my-string-to-local-date-converter: true
    my-string-to-local-date-time-converter: true
    my-string-to-number-converter-factory: true
#    resource-handlers: false
#    minio:
#      endpoint: http://172.29.143.35:9000
#      access-key: minioadmin
#      secret-key: minioadmin
#      default-bucket: taoq-boot

