# 本机开发环境

# 配置数据源信息(此处使用了 p6spy 插件统计 SQL 执行时间，仅用于开发阶段)
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    password: root
    url: jdbc:p6spy:mysql://localhost:3306/iot?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    hikari:
      pool-name: hikari

# 配置日志文件
logging:
  level:
    tech.taoq: debug
    # org.springframework.web: debug

knife4j:
  enable: true
