# Spring 相关配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lsw?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      pool-name: hikari
  main:
    banner-mode: off
  flyway:
    # 开启 flyway
    enabled: false
    # 禁用数据库清理
    clean-disabled: true
    # 迁移时发现目标DB非空，且带有没有元数据的表时，是否自动执行基准迁移
    baseline-on-migrate: true
    # 与 baseline-on-migrate: true 搭配使用
    baseline-version: 0
    # 迁移脚本的位置
    locations: classpath:/flyway/

# 配置端口号和应用路径
server:
  port: 8089
  servlet:
    context-path: /lsw
  shutdown: GRACEFUL

# Sa-Token 配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true

# 配置 MyBatisPlus 日志和别名包
mybatis-plus:
  config-location:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false

# tlog 配置
tlog:
  pattern: $traceId

# knife4j 配置
knife4j:
  # 开启增强配置
  enable: true
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: false
    # Basic认证用户名
    username: wms
    # Basic认证密码
    password: wms
  documents:
    -
      group: default group
      name: 文档使用说明
      # 某一个文件夹下所有的.md文件
      locations: classpath:markdown/*

# forest 配置
forest:
  # 转换器配置，支持 json, xml, text, binary 四种数据类型的配置
  converters:
    # JSON转换器
    json:
      # JSON转换器设置为GSON转换器
      # type: com.dtflys.forest.converter.json.ForestGsonConverter
      # 同理，也可以设置成 Fastjson 或 Jackson 的转换器
      # type: com.dtflys.forest.converter.json.ForestFastjsonConverter
      type: com.dtflys.forest.converter.json.ForestJacksonConverter
  ## 日志总开关，打开/关闭Forest请求/响应日志（默认为 true）
  log-enabled: true
  ## 打开/关闭Forest请求日志（默认为 true）
  log-request: true
  ## 打开/关闭Forest响应状态日志（默认为 true）
  log-response-status: true
  ## 打开/关闭Forest响应内容日志（默认为 false）
  log-response-content: true

# actuator 配置
# 优雅停机 curl -X POST http://localhost:8089/lsw/monitor/shutdown
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "shutdown"
      base-path: /monitor